# Generated by Django 4.1.6 on 2023-02-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/default.webp', upload_to='static/images'),
        ),
    ]
